import { sequelize } from '../config/database.js';
import UserFactory from './User.js';
import VerificationTokenFactory from './VerificationToken.js';
import PasswordResetTokenFactory from './PasswordResetToken.js';
import TailorProfileFactory from './TailorProfile.js';
import KycDocumentFactory from './KycDocument.js';
import BookingFactory from './Booking.js';
import EscrowTransactionFactory from './EscrowTransaction.js';
import DeliveryTrackingFactory from './DeliveryTracking.js';
import MessageFactory from './Message.js';
import PricingPlanFactory from './PricingPlan.js';
import ReviewFactory from './Review.js';
import DisputeFactory from './Dispute.js';
import KycRequirementFactory from './KycRequirement.js';
import GalleryItemFactory from './GalleryItem.js';

const User = UserFactory(sequelize);
const VerificationToken = VerificationTokenFactory(sequelize);
const PasswordResetToken = PasswordResetTokenFactory(sequelize);
const TailorProfile = TailorProfileFactory(sequelize);
const KycDocument = KycDocumentFactory(sequelize);
const Booking = BookingFactory(sequelize);
const EscrowTransaction = EscrowTransactionFactory(sequelize);
const DeliveryTracking = DeliveryTrackingFactory(sequelize);
const Message = MessageFactory(sequelize);
const PricingPlan = PricingPlanFactory(sequelize);
const Review = ReviewFactory(sequelize);
const Dispute = DisputeFactory(sequelize);
const KycRequirement = KycRequirementFactory(sequelize);
const GalleryItem = GalleryItemFactory(sequelize);

// Associations
VerificationToken.belongsTo(User, { foreignKey: 'user_id' });
PasswordResetToken.belongsTo(User, { foreignKey: 'user_id' });
User.hasMany(VerificationToken, { foreignKey: 'user_id' });
User.hasMany(PasswordResetToken, { foreignKey: 'user_id' });
TailorProfile.belongsTo(User, { foreignKey: 'user_id' });
User.hasOne(TailorProfile, { foreignKey: 'user_id' });
KycDocument.belongsTo(User, { foreignKey: 'user_id' });
User.hasMany(KycDocument, { foreignKey: 'user_id' });
GalleryItem.belongsTo(User, { foreignKey: 'user_id' });
User.hasMany(GalleryItem, { foreignKey: 'user_id' });
Booking.belongsTo(User, { as: 'customer', foreignKey: 'customer_id' });
Booking.belongsTo(User, { as: 'tailor', foreignKey: 'tailor_id' });
User.hasMany(Booking, { as: 'customerBookings', foreignKey: 'customer_id' });
User.hasMany(Booking, { as: 'tailorBookings', foreignKey: 'tailor_id' });
EscrowTransaction.belongsTo(Booking, { foreignKey: 'booking_id' });
Booking.hasMany(EscrowTransaction, { foreignKey: 'booking_id' });
DeliveryTracking.belongsTo(Booking, { foreignKey: 'booking_id' });
Booking.hasOne(DeliveryTracking, { foreignKey: 'booking_id' });
Message.belongsTo(Booking, { foreignKey: 'booking_id' });
Message.belongsTo(User, { foreignKey: 'sender_id' });
Booking.hasMany(Message, { foreignKey: 'booking_id' });
PricingPlan.belongsTo(User, { foreignKey: 'user_id' });
User.hasMany(PricingPlan, { foreignKey: 'user_id' });
Review.belongsTo(User, { as: 'customer', foreignKey: 'customer_id' });
Review.belongsTo(User, { as: 'tailor', foreignKey: 'tailor_id' });
Review.belongsTo(Booking, { foreignKey: 'booking_id' });
Booking.hasMany(Review, { foreignKey: 'booking_id' });
Dispute.belongsTo(Booking, { foreignKey: 'booking_id' });
Dispute.belongsTo(User, { as: 'raised_by', foreignKey: 'raised_by_user_id' });
Booking.hasMany(Dispute, { foreignKey: 'booking_id' });

export { sequelize, User, VerificationToken, PasswordResetToken, TailorProfile, KycDocument, Booking, EscrowTransaction, DeliveryTracking, Message, PricingPlan, Review, Dispute, KycRequirement, GalleryItem };